[BROKEN] Remove `Copy + Eq` supertraits from `EnumSetType`.
This is currently impossible because:

1. `#[derive(Eq)]` on `EnumSet<T>` sets a bound of `T: Eq` on the generated `Eq` implementation (and likewise for `PartialEq`). Therefore, `Eq` and `PartialEq` must be implemented manually on `EnumSet`. [This problem probably won't be solved any time soon.](https://github.com/rust-lang/rust/issues/26925)
2. `EnumSet` constants cannot be used in patterns if they use a non-derived `Eq` implementation:

```
error: to use a constant of type `enumset::EnumSet` in a pattern, `enumset::EnumSet` must be annotated with `#[derive(PartialEq, Eq)]`
   --> enumset/tests/ops.rs:286:17
    |
286 |                 CONST_SET => { /* ok */ }
    |                 ^^^^^^^^^
```

😞